input_config:
  tab_regex: 'Detail_\d+'

output_config:
  enrichment_col_prefix: keepa_
  enrichment_cols:  # TODO: convert this to a map and add types
    - title
    - description
    - min_price
    - max_price
    - avg_price
    - category_tree
    - sales_rank

execution_params: 
  platform: unix  # windows or unix
  input_dir: ~/deal_analyzer_input
  output_dir: ./results
  lookback_days: 30
  domain: CA
  log_name: deal_analyzer.log

